# Generated by Django 3.2.16 on 2023-05-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('stripe_checkout_link', models.URLField()),
            ],
        ),
    ]
